# ================= APP =================
spring.application.name=BankProject
server.port=8282

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Shivam@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ================= SESSION =================
server.servlet.session.timeout=30m

# ================= THYMELEAF =================
spring.thymeleaf.cache=false

# ================= STATIC =================
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
spring.mvc.throw-exception-if-no-handler-found=true

# ================= LOGGING =================
logging.level.com.springboot=DEBUG

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivambrahman03@gmail.com
spring.mail.password=lkbzxsnpabxqnpev


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= TIMEOUT (OPTIONAL) =================
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000